### ISSUE TITLE
aria-dropeffect="none" don't change to "move"

### ISSUE THREAD

**Issue by lucju04** [Vivify-Ideas/vue-draggable#10]
First of all thanks for you library it's very helpful !

I have a simple issue... When a drag and drop a element, the aria-dropeffect attribut on my ul elements don't change to "move". Only the last ul got this. I'm sad because I can't use ul[aria-dropeffect="move"] for my css =( 

Did you already seen this issue ? 

FYI my config: 

`draggable: {
        dropzoneSelector: "ul",
	draggableSelector: 'li',
	excludeOlderBrowsers: true,
	multipleDropzonesItemsDraggingEnabled: true,
	showDropzoneAreas: true,
}`

Hope you can save me about this point ^^

**Comment by nikolasp** [comment]
Hi @lucju04,
 
I haven't noticed this issue. May you provide simple CodeSandbox example with the issue stated above so I can inspect that further? 

Thanks for feedback

**Comment by lucju04** [comment]
Yeah I will try to do that ASAP ;)
