### ISSUE TITLE
Drag and drop within single container (reorder elements)

### ISSUE THREAD

**Issue by IlyaSemenov** [Vivify-Ideas/vue-draggable#13]
Is that possible to use the library on a single draggable container, to reorder elements in a list with drag and drop?

I would expect the behaviour similar to your codepen example (https://codepen.io/nikolasp/pen/yvpWJR) when one drags an item from List 1 to List 2 (gray placeholders etc.).

**Comment by nikolasp** [comment]
Hi @IlyaSemenov,
Thanks for the feedback!
I've published new version 1.0.8 with possibility to reorder elements in same column. I've updated [demo](https://codepen.io/nikolasp/pen/yvpWJR) with new version so you can check this out. 
I hope this is exactly what you have expected. 😄

**Comment by IlyaSemenov** [comment]
Thank you! This is exactly what I needed.
