### ISSUE TITLE
Detect dragout

### ISSUE THREAD

**Issue by buffet-time** [Vivify-Ideas/vue-draggable#14]
Is it possible to detect when an element that was being dragged is dragged out of valid area? For use to execute a function on this "dragout" example would be dragging a tab in chrome out of its container and it opening a new window.

**Comment by nikolasp** [comment]
Hi @buffet-time,

Yes, it's possible to detect when element is dropped out valid area (droptargets). You have 3 callbacks available (`onDrop`, `onDragstart`, `onDragend`), but for this you can use `onDragend` and you can check `event.droptarget`. If `event.droptarget` is null you can be sure that element is dropped outside valid area. I've updated [demo](https://codepen.io/nikolasp/pen/yvpWJR) with code below so you can check this out.

```
      onDragend(event) {
        // to detect if draggable element is dropped out
        if (!event.droptarget) {
          console.log('event is dropped out');
        }
      }
```
