### ISSUE TITLE
Selector to define drag handle

### ISSUE THREAD

**Issue by IlyaSemenov** [Vivify-Ideas/vue-draggable#16]
It would be great to allow only certain part of the draggable elements to actually initiate drag. Example of such UI is below:

<img width="776" alt="screenshot 2019-01-19 at 13 03 22" src="https://user-images.githubusercontent.com/128121/51422948-ae2d1c80-1bea-11e9-8adb-ecf347f0daed.png">

Only the hamburger icons should be used for dragging, however the entire element should be dragged.

**Comment by nikolasp** [comment]
I've published v1.1.0 with possibility to define handle element. 🚀 
Take a look at [example](https://codesandbox.io/s/mz1vjxk9mp)
