### ISSUE TITLE
Example using Vue Data

### ISSUE THREAD

**Issue by nwittwer** [Vivify-Ideas/vue-draggable#17]
Would be great to see an example for when the draggable items come from a `v-for` loop. After dragging an item to a new index, I thought my underlying data would also be updated ("reactive").

**Scenario:**
I use `v-for` for each item in my `this.myList`, and generate a DOM element for each item. Those DOM elements become draggable using this plugin.

```js
data() {
  return {
    myList: [
      { title: a },
      { title: b }
      { title: c }
    ]
  }
}
```

Imagine this is how the DOM starts (using `v-for` on each item in `myList`):
```
A, B, C
```

After reordering the DOM elements via this plugin, the DOM may look like:
```
B, C, A
```

However, the underlying data is still:
```js
myList: [
  { title: a },
  { title: b }
  { title: c }
]
```

How would you recommend updating the `data` based on the new order?

**Comment by nikolasp** [comment]
Hi @nwittwer,

I've made small [codesandbox example](https://codesandbox.io/s/7ml5x9p6pj) how to work with reactive data in Vue. I'll add this to official documentation for this library. I hope I've answered your question.

**Comment by nwittwer** [comment]
@nikolasp Very cool, thanks!
