### ISSUE TITLE
integration with application framework (quasar)

### ISSUE THREAD

**Issue by qyloxe** [Vivify-Ideas/vue-draggable#22]
Is there a possibility to create an example which works with Quasar Framework? For example dragging from one qlist to another qlist or from qtree to another qtree (with model synchronization)? This library looks great (I love the concept of datasets), but I wonder if it is suitable for real world integration with application frameworks. Here is quasar list component:

https://quasar-framework.org/components/lists-and-list-items.html

**Comment by nikolasp** [comment]
Hi @qyloxe,

Yes, it's possible to use vue-draggable with Quasar Framework. 😃 
I've created small [example](https://codesandbox.io/s/94yv5v6vrw?module=%2Fcomponents%2FHello.vue) with [Quasar Lists&Items](https://quasar-framework.org/components/lists-and-list-items.html). Model data is printed at top so you can check reactivity (model synchronization).
I hope this answers your question.

[![Edit VueDraggable with Quasar Lists](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/94yv5v6vrw?module=%2Fcomponents%2FHello.vue)

**Comment by qyloxe** [comment]
IMHO this library is one of the best DND I ever seen. The ingenious part is event.dataset and the model mechanic. I think in the future this library will change the world :-)

Anyway, in the example there are some quirks, I'd like to point your attention:

step 1: drag item 1 before item 3. It is moved after item 4.
step 2: drag item 2 before item 3. It is moved after item 4.
step 3: hold ctrl and select item 4 and item 2
step 4: drag two selected items to list 1. this is the effect:

![image](https://user-images.githubusercontent.com/467508/51944594-ba9c4b00-241c-11e9-9416-4e2d18ab9acb.png)

the model for items 2 and 4 is properly updated, but rendering has duplicated items.
drag and drop in one list properly reorders items. drop onto another list always appends the item.

so, I wonder if code for method reorderItems should be somehow adjusted to specific framework ie quasar. It would be hard, to every time write such complicated code for reorder/diff/insert/update/copy items between models. Maybe there could be standard methods for example for simple move, simple copy, multiple move, multiple copy etc. and those standard methods could be used as mixins or as another library for example vue-draggable-quasar. I do not know, just thinking.

Anyway, it is AWESOME library, I'm curious if above behaviour could be fixed on the vue-draggable level or it needs something specific in handler method in quasar environment.

I think, we should create working example, as a good test, for properly using DND with quasar lists, and only after that try to write more complicated DND  in hierarchical models (DND). Your library is amazing, because in essence it is model DND and not visual/DOM dnd. And in this way, it is aligned to a soul of VUE and concepts of reactive programming.

**Comment by nikolasp** [comment]
@qyloxe Thanks for the feedback.  I'll check this asap.
I've created this example really quick so I didn't have time to test it properly.
I can't say that library, in essence, is model DND, but that's something I'm trying to achieve eventually and keep things simple as possible. Simplicity is the main reason why Vue is popular today.

**Comment by qyloxe** [comment]
Hmm, I thought a little and it seems, that your library could really be something innovative. Why? Well, every other DND library uses events like OnDrop, OnDrag, OnDragging etc. All those event are linked to DOM elements. But your library is the first, which could also generate events strictly operating on the models. And let the Vue do the rest of the visual work. You could generate specific events where vue instance receives events which specifically tells which model and which elements are inserted, appended, removed. Of course, you should generate DOM based events, too, but honestly - if I want to use DND library, then I prefer not to mess with visuals, but I need to update my datas based on user interaction. As for now, it is rather hard to write specific adapter which based on DOM behaviour should infer what to do with the underlying models. If you could generate "model based" events, that you do not need to write one, very, very complicated "OnDropped" function, but you could just react to simple, data structure change events. For example, lets assume, that your library detected or had declared, that developer wants to allow dragging from model "Users" and allow dropping on model "Groups". Then, you could emit such events:

OnBeforeRemove(model,index list) -> called in this example with (users collection and list of selected indexes from said collection). you could return (as a promise of course) structure in which you can specify if you allow to remove items, or specify your own items, and setting your own user data.

OnBeforeInsert(src_model,dst_model,src_index_list,dst_index,user_data) -> called in this example with (users collection, groups collection, list od indexes of selected items from source model eventually modified in return value of OnBeforeRemove, index of position in which users dropped those items, and user data which were updated in return value of OnBeforeInsert event - or other events where in user_data those events could set their own context).

Having such model based events, allows to write DND adapters very simply. In your example reorderItems adapter is VERY complicated. I'm sure it is prone to errors, and it requires from developer thinking about whole mechanic of diff algorithm between models where his information is based on DOM bahaviour. It is a lot od decisions. With model based events, those decision are simple - am I allowing to move from this list or nor, am I allowing to insert those items or not etc.

I hope it makes sense to you.

**Comment by nikolasp** [comment]
Yes, that makes sense. As I said before it's something I'm trying to achieve.

>  I prefer not to mess with visuals

That's my intention, because I think this could affect Vue itself and cause template rendering issues when we are working with structure directive like `v-for`.
 
Model manipulation is something that worries me because I don't wanna make something that works strictly with declared model structures. 
Basically my idea is to extend `onDrop` callback params with some model related data, so you don't need to write as you said such complex logic and also to keep the library backward compatibility. What do you think about this?

**Comment by qyloxe** [comment]
well, backward compatibility is overrated. this is not a library with global reach, but IMHO it could be if you take a leap of faith and go where vue is going :-) What I mean, is that Vue encourages to not think in terms of DOM elements (which it virtualizes btw), but in terms of model changes, where those changes causes simple DOM updates only in places where it is necessary and nowhere else. Vue has a concept of components, so communication between components is realized preferably one-way from parent to child by references and from child to parent by simple events. Communication between sibling componenst is in Vue realized either by global events bus (for thos who couldn't live without events) or ... by VueX and state changes. Those state changes is a preferred architecture of the Vue ideology.
You are writing something amazing, which is embedded in Vue ecosystem, so you shouldn't prefer the "old" way of thinking and encourage to work with dnd omitting declared model structures. That's why your work is ingenious, because now, you can allow the sibling communication between components with dnd library. This communication between components is a model also. As for now, your library is able to detect which data model is associated with dragged/dropped DOM element which is great - but - in the end - you should even communicate those model changes with specific Vue components. But - as for now, let's just keep the model changes/updates/inserts/removals and the rest will architecturally show itself.
What to do next? Well, I will be available after 10th february. I think that it could be helpful to have another git repository "vue-draggable-example-quasar" with quasar project in which we could have some use cases:
- 3 q-lists
- 2 q-trees
- 1 q-list for "clipboard" for temporary keeping the items
And in this use case, it should be implemented the dnd scenarios of exchanging items between all those components. I could help with that - after 10th february. It would be awesome to have on the component level something which makes this component draggable or droppable.

**Comment by nikolasp** [comment]
In the meantime, I've started working on improvements regarding this. 
It's work in progress, but take a look at updated [codesandbox demo](https://codesandbox.io/s/94yv5v6vrw?module=%2Fcomponents%2FHello.vue). 
Beta version of the library `vue-draggable@2.0.0-beta.0` is published with new events introduced. 

Attach custom events on group elements and you can write your own logic to work with model data.

```html
@added="added($event, group)"
@removed="removed($event, group)"
@reordered="reordered($event, group)"
```

Every event has `detail` property formed like this
```js
{
  ids: array, // array of ids
  index: number // index of next element in dropped group
}
```

I've also created `vue-draggable-with-quasar` repo so you can try this also locally.
https://github.com/nikolasp/vue-draggable-with-quasar

I'm open for all suggestions regarding this implementation.

**Comment by nikolasp** [comment]
Released v2.0.0 🎉

**Comment by altShiftDev** [comment]
@nikolasp could you elaborate on how you integrate with quasar?

I'm on the latest quasar version and it no longer uses a main.js file. External libraries are pulled in with plugins and yours doesn't seem to work when I create a plugin for it.

My plugin (registered in quasar.conf.js):
```javascript
import VueDraggable from 'vue-draggable'

export default ({ Vue }) => {
  Vue.use(VueDraggable)
}
```
I then copy/pasted everything from Hello.vue in your link: https://codesandbox.io/s/p9vzv6qko7 
Am I missing a step?

**Comment by missionz3r0** [comment]
@nikolasp Apologies for resurrecting this thread, but digging around only finds this one year old post. And I have the same question as altShiftDev did up there.

Do you mind elaborating? Because I can't for the life of me manage to get the two libraries to behave together.

**Comment by nikolasp** [comment]
Hi @missionz3r0 , @altShiftDev 

No need for apology. Thanks for the feedback. 
I've updated old repo with new Quasar version and integrated `vue-draggable` so please take a look at that.
https://github.com/nikolasp/vue-draggable-with-quasar

## STEPS:
VueDraggable plugin is registered through separate boot file (https://quasar.dev/quasar-cli/cli-documentation/boot-files#Introduction), which I have created with quasar-cli command `quasar new boot vue-draggable`. 
Created boot file `vue-draggable.js` should look like this
```js
import VueDraggable from 'vue-draggable'

export default async ({ Vue }) => {
  Vue.use(VueDraggable)
}
```

The last step is updating of `quasar.conf.js` boot section
```js
    boot: [
      'vue-draggable'
    ],
```
And that's it... 🎉 
 
PS. Don't forget to install quasar list components before usage... 
For our example I just used these:
```js
components: [
        'QList',
        'QItem',
        'QItemSection',
        'QItemLabel'
],
...
```

**Comment by missionz3r0** [comment]
well, I feel like a dunce now. I'd gotten everything except explicitly defining the components in quasar.conf.js. That's what I was missing, and thank you for taking the time to update this issue.
