### ISSUE TITLE
Unusable with a large ammount of items

### ISSUE THREAD

**Issue by sadortun** [Vivify-Ideas/vue-draggable#24]
**Describe the bug**
Hi,

vue-draggable is unusable with a large amount of items

**To Reproduce**
1. Go to https://vivify-ideas.github.io/vue-draggable/example/#working-with-reactive-data
2. Add 5000 to 20 000 items in the list(s)
3. Run the example
4. Window will freeze for a good 30-60 seconds, then dragging an item takes 2-5 seconds.

**Expected behavior**
Usable draggable lists

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Comment by nikolasp** [comment]
Hi @sadortun,

Thanks for the feedback. It's something I'm working on. 
Basically with new version of the library reactivity mode is default and we will probably introduce new group events (added, removed, reordered). 
In the meantime you can look at beta example made for this use case.
[![Edit VueDraggable Reactivity](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9nqlz75lo)

**Comment by nikolasp** [comment]
Released v2.0.0 🎉
