### ISSUE TITLE
This doesn't work if I change the keys

### ISSUE THREAD

**Issue by baig772** [Vivify-Ideas/vue-draggable#28]
**Issue**
If I change the keys from `groups` and `items` to something else, it doesn't work

**To Reproduce**
Try with the `data` key in below  `JSON`
`{"message":"","data":{"zones":[{"id":1,"name":"Zone 1","pens":[{"id":1,"zone_id":1,"name":"Pen 1","pen_number":1,"hospital_pen":0,"quarantine_pen":0}]}]}}`

**Comment by nikolasp** [comment]
Hi @baig772, 
Thanks for the feedback.
You can pass to [renderless component](https://github.com/Vivify-Ideas/vue-draggable/blob/master/src/components/vue-draggable-group.component.js) itemsKey prop and change default value `items` to  `pens`.
Please take a look into [codesandbox example](https://codesandbox.io/embed/xll48mrznw) I've made. 
However, I will extend README section with this info.
