### ISSUE TITLE
possibility to detect drop in same container

### ISSUE THREAD

**Issue by breadlesscode** [Vivify-Ideas/vue-draggable#3]
Hi,

I want to display a trash bin if an element starts to drag and I want to hidde it if the element is dropped but if you drop an element in the same container, no drop event is fired. 

Can you add something like:  dragstop? That would be awesome :relaxed:

**Comment by nikolasp** [comment]
Hi,

This option will be available in two days max. Thank you for your interest
in this library...

**Comment by nikolasp** [comment]
Hi,

I've just pushed this to master and published to npm... Test it and if there are some issues we will resolve them as always... 😄

**Comment by breadlesscode** [comment]
Thanks! I will test it soon 😍
