### ISSUE TITLE
two issues with text inputs inside draggable list-elements

### ISSUE THREAD

**Issue by irrg** [Vivify-Ideas/vue-draggable#30]
**Describe the bug**
We're building a complex UI where an element (a file) becomes draggable to another category when it's set to 'edit' mode. In edit mode, we add a "handle" that we specify using the `handlerSelector` option and show the filename of the item in an input so the user can rename the file

with `vue-draggable`, there's two undesirable situation that come from trying to use an input inside a draggable element:

1. Specify a `handlerSelector`: The input can no longer be targeted with the mouse. Cursor cannot be placed/focus can not be given.
2. don't specify a `handlerSelector`: Trying to select text inside the input triggers drag-mode

**To Reproduce**
This is a simplified example of what's happening.
1. Go to https://codesandbox.io/s/0q0kx50m30

to reproduce the scenario without a handlerSelector, comment out line 58.

**Expected behavior**
Expect text to be selectable/editable inside the input without triggering drag-mode.

**Desktop (please complete the following information):**
 - MacOS Mojave 10.14
 -  Chrome 
- version 70

**Comment by nikolasp** [comment]
Hi @irrg ,

Thanks to your really good description and CodeSandbox example I was able to find the cause of the issue. 😄 I've fixed the issue and new version v2.0.2 is published. Just try v2.0.2 and everything with stated `handlerSelector` should work. 

However, for the second example (don't specify a handlerSelector) I couldn't reproduce the issue. Selecting input works at least on my machine. The only difference in comparison to your environment is that I'm using newer version of chrome (v73.0.3683.103).

**Comment by irrg** [comment]
Amazing, thank you so much. I'll see if I can describe the second issue better…basically, use your mouse to start selecting text and then drag to the right. I'll see if it's still an issue with v73!

**Comment by tpyszko** [comment]
Hi, 
I have the same issue as @irrg 
In v2.0.2 I can set the cursor inside input (when you click input cursor appears at the end) - but I cannot select certain text inside the input.

**To reproduce:** 
Go to the codesandbox, update vue-draggable to the latest version and try to select text "item" in one of the inputs.

Thanks for your help

**Comment by divya2808** [comment]
I am seeing the same issue. I tried to select something in the input box inside draggable list item and it would move the item on mousedown and drag and not select the text. How would I solve it?
