### ISSUE TITLE
name likes vuedraggable but ....

### ISSUE THREAD

**Issue by XQY279** [Vivify-Ideas/vue-draggable#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

plaese rename you product

**Comment by nikolasp** [comment]
Hi @XQY279, 
I'm not sure what is the main issue based on provided description. Why do we need to change the name of library? You opened this issue with really poor description of problem, so please update the issue with more details or close the issue. Thanks
