### ISSUE TITLE
Is animation supported?

### ISSUE THREAD

**Issue by mityukov** [Vivify-Ideas/vue-draggable#4]
I'd like to confirm on the animation possibility here. What i mean is the following: when I change position of an element, it switches with another one instantly, which makes it hard to see that anything has actually happened just now. It would be good to have one of the following kinds:

1. Animate another (over which I'm hovering) element's position change;

- or (better) - 

2. Make neighboring elements (those, between which I'm going to drop the currently dragged one) to slide a bit in opposite directions.

**Comment by nikolasp** [comment]
Hi, 
It's not supported yet... There are plans to implement this... In a few weeks will be available...

**Comment by typerory** [comment]
Does this work on a tablet?

**Comment by atilkan** [comment]
few years maybe.

**Comment by nikolasp** [comment]
@atilkan maybe faster 😅

**Comment by nikolasp** [comment]
https://github.com/Vivify-Ideas/vue-draggable/commit/3c62b3bf32300329f27380df695d0b72b43cb688

**Comment by atilkan** [comment]
great.
