### ISSUE TITLE
Export VueDraggableDirective as separate name

### ISSUE THREAD

**Issue by alex-nextraq** [Vivify-Ideas/vue-draggable#49]
**Is your feature request related to a problem? Please describe.**
I would like to use this directive in specific components, but not globally.

**Describe the solution you'd like**
if the VueDraggableDirective from index.js could be exported, I could then add it to a specific component within its `directive` section

**Describe alternatives you've considered**
I've considered copying the directive definition into my own project and using it as needed, but figured iId see if this was something y'all might add first.

**Comment by nikolasp** [comment]
Hi @alex-nextraq ,
Thanks for the feedback. 
`VueDraggableDirective` is exported and section about local directive usage is added in readme.
