### ISSUE TITLE
touch support

### ISSUE THREAD

**Issue by aarcane** [Vivify-Ideas/vue-draggable#5]
Currently touch events don't seem to be registered or handled properly

**Comment by Tsaukpaetra** [comment]
That's probably due to touch events not being able to be drag events...

**Comment by nikolasp** [comment]
@aarcane You will need to use polyfill that enables HTML5 drag and drop for mobile devices... 
Maybe this will help you https://github.com/Bernardo-Castilho/dragdroptouch

**Comment by mesqueeb** [comment]
Is touch support going to be added by default? I believe people who build cordova apps with Vue would have great benefit from this!

I looked at the polypill but it has no NPM install and I believe most people would love to have this built in natively to vue-draggable! 🗽
