### ISSUE TITLE
IE 11 support for customEvent

### ISSUE THREAD

**Issue by stwalter01** [Vivify-Ideas/vue-draggable#50]
I manipulated the polyfills with a custom even function to provide support in IE11. 
Simply adding the following adds support.

// source: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent
(function() {
  if (typeof window.CustomEvent === "function") return false

  function CustomEvent(event, params) {
    params = params || { bubbles: false, cancelable: false, detail: undefined }
    var evt = document.createEvent("CustomEvent")
    evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail)
    return evt
  }

  CustomEvent.prototype = window.Event.prototype

  window.CustomEvent = CustomEvent
})()

**Comment by nikolasp** [comment]
Hi @stwalter01,

Thanks for the feedback.
https://github.com/Vivify-Ideas/vue-draggable/pull/31/files
We can probably merge opened PR.

**Comment by stwalter01** [comment]
Thanks, any chance you can publish/release so npm install uses the latest code?

Thanks,
Sam

**Comment by nikolasp** [comment]
Hi Sam,
Yeah, it will be available tomorrow. 
Sorry for the delay.

**Comment by nikolasp** [comment]
v2.0.3 with CustomEvent polyfill is published.
