### ISSUE TITLE
How to prevent the item from be added in the onDragEnd: function()

### ISSUE THREAD

**Issue by ty7466** [Vivify-Ideas/vue-draggable#6]
I want to capture the item being dropped and prevent it from it actually being added to the DOM. Is this possible?

**Comment by nikolasp** [comment]
Hi @ty7466,
Thank you for your interest in this package...

I've published new version v1.0.5 where you have possibility to stop d&d in two callbacks(onDragstart and onDragend) just by calling `event.stop()` method. You can try this if you uncomment options lines in copepen.io (https://codepen.io/nikolasp/pen/yvpWJR) 

```
    onDragstart(event) {
        event.stop();
    },
    onDragend(event) {
        event.stop();
    }
```

This event param contains a lot more options so you can conditionally stop D&D... For more look at readme...
I hope this will help you and once again thank you for feedback. 😄
