### ISSUE TITLE
It doesn't work with iview Card components

### ISSUE THREAD

**Issue by hooklife** [Vivify-Ideas/vue-draggable#67]
[![Edit frosty-lichterman-bfekg](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-lichterman-bfekg?fontsize=14&hidenavigation=1&theme=dark)

**Comment by nikolasp** [comment]
Hi @hooklife,

There are 2 things you have to change to have fully working solution:
- Moving card component outside `vue-draggable-group`
- You have changed items property name from `items` to `tasks` so in that case `itemsKey` prop must be passed to `vue-draggable-group` component (https://github.com/Vivify-Ideas/vue-draggable#reactivity-handling-and-renderless-component)

With this in mind, working solution would look like this:
```html
<template>
  <div id="app">
    <div v-drag-and-drop:options="options" class="project-details">
      <card class="task-group" v-for="group in taskGroups" :key="group.id">
        <vue-draggable-group
          v-model="group.tasks"
          :groups="taskGroups"
          :key="group.id"
          :data-id="group.id"
          itemsKey="tasks"
        >
          <ul>
            <li v-for="item in group.tasks" :key="item.id" :data-id="item.id">
              <label v-text="item.name"></label>
            </li>
          </ul>
        </vue-draggable-group>
      </card>
    </div>
  </div>
</template>
```

Hopefully that's the answer you were looking for. 
All the best!
